#include <Windows.h>
#include <stdio.h>

#include "resource.h"
#include "Proc.h"

State state;
void InitState(State*);

int WINAPI wWinMain(HINSTANCE hInstance, HINSTANCE hPrevIns, PWSTR pCmdLine, int nCmdShow) {
    InitState(&state);
	DialogBoxParam(hInstance, MAKEINTRESOURCE(IDD_DIALOG1), NULL, DlgProc1, (LPARAM)&state);

}


CONST WCHAR* MockArr[200] = {
    L"Your future is being stuck with me forever… FOREVER.",
    L"The crystal ball says you’ll never escape this window." ,
	L"No matter how old you get, your brain will stay on vacation.",
	L"Your future is darker than your search history.",
	L"The stars say you’ll be a failure forever.",
	L"Your future is the same as your past: useless.",
	L"You will grow older, but never wiser.",
	L"The only thing growing in your life is regret.",
	L"Even fate is embarrassed to know your name.",
	L"Your destiny is tripping over the same rock forever.",
    L"Your life story will be called 'mistakes only.'",
    L"At your age, others shine. You flicker like a dying bulb.",
    L"Your future is just you talking to walls.",
    L"The stars say you’ll be broke, alone, and ignored.",
    L"Even your future tried to run away.",
    L"Your destiny is being the punchline forever.",
    L"The crystal ball showed me nothing—it gave up on you.",
    L"You are proof that not everyone has a purpose.",
    L"Your destiny is second place forever.",
    L"And finally… your future is being stuck with me forever… FOREVER.",
    L"Your future is falling flat on your face again and again.",
    L"The stars say you will always lose.",
    L"Your name will be used as a warning, not a memory.",
    L"You will spend your life chasing things you’ll never get.",
    L"Your future is nothing but failure on repeat.",
    L"The stars say your life will be one long bad joke.",
    L"Your destiny is crying in empty rooms.",
    L"Even your shadow will walk away from you.",
    L"Your future is a never-ending mistake.",
    L"You will always be the slow one, the weak one, the lost one.",
    L"The crystal ball cracked rather than see you again.",
    L"Your future is everyone laughing at you, not with you.",
    L"You will spend forever stuck in dead ends.",
    L"Your destiny is to be ignored until the end.",
    L"The stars say you will never matter.",
    L"Your life is a broken record of regret.",
    L"Your future is getting older but going nowhere.",
    L"Even fate doesn’t want you.",
    L"You will spend your days waiting for nothing.",
    L"Your future is worse than you can imagine.",
    L"The stars say failure will be your best friend.",
    L"Your destiny is doors closing forever.",
    L"You will always come last.",
    L"Your life will be the story people skip.",
    L"Your future is a storm with no shelter.",
    L"You will never be the winner, only the joke.",
    L"The stars say you’ll always want more and get less.",
    L"Your destiny is endless letdowns.",
    L"Your future is the world forgetting you exist.",
    L"You will trip even when the ground is flat.",
    L"The stars say you’ll spend your life chasing shadows.",
    L"Your destiny is every wrong turn forever.",
    L"You will always be a mistake someone regrets.",
    L"Your future is pain without purpose.",
    L"The stars say you’ll fail even at easy things.",
    L"You will be remembered only as the fool.",
    L"Your destiny is falling and never getting up.",
    L"Your future is people leaving you behind.",
    L"The stars say you will always be unwanted.",
    L"Your life is a waste with no end.",
    L"You will always get lost, even with a map.",
    L"Your future is nothing but broken dreams.",
    L"Your destiny is to never be good enough.",
    L"The stars say you will always be alone.",
    L"You will beg for help and still be ignored.",
    L"Your future is the sound of doors slamming shut.",
    L"Your destiny is an empty road forever.",
    L"Your life is a mirror showing nothing back.",
    L"The stars say you’ll be stuck in circles forever.",
    L"Your future is endless dead ends.",
    L"You will always be too late for everything.",
    L"Your destiny is being forgotten while alive.",
    L"The stars say you’ll always be weaker than others.",
    L"Your future is a scream no one hears.",
    L"You will always be stuck in the wrong place.",
    L"Your destiny is cold nights and no comfort.",
    L"Your life is proof that not everyone wins.",
    L"The stars say you’ll always be the broken one.",
    L"Your future is falling and falling and falling.",
    L"You will never climb out of the hole you’re in.",
    L"Your destiny is empty hands forever.",
    L"Your future is silence after failure.",
    L"The stars say you’ll never be chosen.",
    L"You will always be the extra, never the main.",
    L"Your destiny is endless waiting.",
    L"Your life is just one long loss.",
    L"Your future is being laughed at forever.",
    L"You will always lose what little you get.",
    L"Your destiny is people pretending you don’t exist.",
    L"The stars say your dreams will always rot.",
    L"Your future is failure written in stone.",
    L"You will spend your life watching others win.",
    L"Your destiny is a road that leads nowhere.",
    L"Your future is being last in every line.",
    L"You will always be the one left behind.",
    L"Your destiny is endless nights with no light.",
    L"The stars say you’ll always be trapped.",
    L"Your life is a joke no one likes.",
    L"Your future is more pain than joy.",
    L"You will never know peace.",
    L"Your destiny is to suffer quietly forever.",
    L"The stars say you’ll die as lost as you live.",
    L"Your future is tears you can’t stop.",
    L"You will always be ignored by everyone.",
    L"Your destiny is regret and nothing else.",
    L"Your life is just failure stacked on failure.",
    L"The stars say you will always be a nobody.",
    L"Your future is misery forever.",
    L"You will always crawl, never walk.",
    L"Your destiny is to be laughed at and forgotten.",
    L"Your future is nothing but closed doors.",
    L"The stars say you’ll be broken forever.",
    L"Your destiny is being stuck with me forever… FOREVER.",
    L"Your future is every wrong step possible.",
    L"You will never escape your mistakes.",
    L"Your destiny is to fall and never rise.",
    L"Your life is a chain of letdowns.",
    L"Your future is forever empty.",
    L"The stars say you will always be a failure.",
    L"Your destiny is misery repeated endlessly.",
    L"You will always be the loser.",
    L"Your future is begging for scraps.",
    L"The stars say nothing good will ever be yours.",
    L"Your destiny is only shame.",
    L"Your life is nothing but wasted time.",
    L"Your future is endless pain.",
    L"You will never be enough.",
    L"Your destiny is to be hated quietly.",
    L"The stars say your story ends badly.",
    L"Your future is broken hopes.",
    L"You will always be stuck in this void.",
    L"Your destiny is to never escape me.",
    L"Your future is nothing but regret and loss.",
    L"You will always be forgotten.",
    L"Your life is trash that no one wants.",
    L"Your destiny is failure forever.",
    L"The stars say you’ll always cry alone.",
    L"Your future is one long nightmare.",
    L"You will never wake up from your mistakes.",
    L"Your destiny is stuck windows forever.",
    L"Your future is being mocked by me endlessly.",
    L"You will always lose, no matter what.",
    L"Your life is proof that fate is cruel.",
    L"Your destiny is suffering forever.",
    L"The stars say nothing good comes to you.",
    L"Your future is a laugh at your expense.",
    L"You will always be trapped in this void.",
    L"Your destiny is my voice forever in your head.",
    L"Your future is endless shame.",
    L"You will never see a happy ending.",
    L"Your life is a bad story on repeat.",
    L"Your destiny is being stuck forever… FOREVER.",
	NULL //Keeping last null to get exact size 
};

void InitState(State* state) {
    state->index = 0;
    state->max_ind = 0;
    state->Arr = MockArr;
    
    //Get max_ind
    while (state->Arr[state->max_ind] != NULL)
        state->max_ind++;
}
